use_frameworks!
target 'LiveSportsTVHD' do
pod 'Google-Mobile-Ads-SDK'
pod 'FAPanels'
pod 'Firebase/Core'
pod 'Firebase/Messaging'
pod 'BMPlayer', '~> 1.3.0'
pod 'Kingfisher', '~> 5.0'
pod 'NVActivityIndicatorView'

end